### PR TITLE
Handle numbers in object types; fixes #241

### LINKED ISSUE #241: Object not display good
Hi all,

I create object catégorie and  2 objects.
But :
There not display good
There not display on element when i create a ticket.
You can see the pics there 
https://forum.glpi-project.org/viewtopic.php?id=168809
Capt
Cap3
Cap2

Can you help me plz ?
Crysy

### PR DESCRIPTION
**Pull request by cedric-anne**
From GLPI 9.4.x, generic objects containing numeric chars are handled correctly in search view.

Problem is the same as in "fields" plugin (see https://github.com/pluginsGLPI/fields/pull/306).

### CODE REVIEW

**Comment by cedric-anne** [comment]
Requires https://github.com/glpi-project/glpi/pull/6056

**Comment by mdz0r** [comment]
Hello,

Is it possible to get a fix for 9.4 ?

**Comment by cedric-anne** [comment]
Hi @mdz0r ,

It uses a migration method that has been introduced in 9.5 branch of GLPI, so it requires to much work to do a 9.4 version of this fix.

Regards

**Comment by mdz0r** [comment]
@cedric-anne : thanks for your answer, do you think it would be possible to get a SQL script to "rename" a genericobject ?
Issue seems to occur only when there are numbers in the object name.

**Comment by mdz0r** [comment]
Found out how but really pain in the ass...

First, backup database and files/_plugins/genericobject

Rename the glpi_plugin_genericobject_old_name[s] tables
Update glpi_plugin_genericobject_types table with new name

Then :
```
update glpi_contracts_items set itemtype = 'new_name' where itemtype='old_name'
update glpi_documents_items set itemtype='new_name' where itemtype='old_name'
update glpi_items_tickets set itemtype='new_name' where itemtype='old_name'
update glpi_items_operatingsystems set itemtype='new_name' where itemtype='old_name'
update glpi_items_deviceprocessors set itemtype='new_name' where itemtype='old_name'
update glpi_items_devicenetworkcards set itemtype='new_name' where itemtype='old_name'
update glpi_items_devicememories set itemtype='new_name' where itemtype='old_name'
update glpi_items_devicefirmwares set itemtype='new_name' where itemtype='old_name'
update glpi_computers_items set itemtype='new_name' where itemtype='old_name'
update glpi_displaypreferences set itemtype='new_name' where itemtype='old_name'
update glpi_infocoms set itemtype='new_name' where itemtype='old_name'
update glpi_logs set itemtype='new_name' where itemtype='old_name'
update glpi_logs set itemtype_link='new_name' where itemtype_link='old_name'
update glpi_plugin_datainjection_mappings set itemtype='new_name' where itemtype='old_name'
update glpi_plugin_datainjection_models set itemtype='new_name' where itemtype='old_name'
```

There are maybe more glpi_items* tables.

Then go to _plugins/genericobject and rename/update all the php class files refering to old_name (in front/ locales/ and inc/.

**Comment by cedric-anne** [comment]
Included in #275

**Pull request closed without merging**
