### PR TITLE
Fix #176: Issue when trying to map fields for data injection

### LINKED ISSUE #176: Issue when tring to map fields for data injection
Hi all,

I'm using the last versions of these 2 plugins.
Datainjection : 2.5.0
GenericObject 2.5.0
I'm under GLPI version 9.2.1

In datainjection, when I created a model and want to map filds for data injection I only have "type" and "Technician in charge of the hardware"

image

Datainjection works fine with the natives models (computer, phones, etc..)

Thx a lot for your help !

### PR DESCRIPTION
**Pull request by pVesian**
Fix issue when injecting genericobjects with datainjection

### CODE REVIEW

**Comment by pVesian** [comment]
@cedric-anne Should I do a new PR on develop branch?

**Comment by cedric-anne** [comment]
Hi,

No, I changed target, so you do not have to do a new PR.

I just need to take time to review it.

Regards

**Comment by pVesian** [comment]
Ok.
You'll notice I've commented the part about `groups_id_tech` because `groups_id` won't appear in the dropdown when `groups_id_tech` is present. I couldn't find a fix for it, maybe you will.

**Comment by cedric-anne** [comment]
I think `linkfield` is already handled for `groups_id_tech` in https://github.com/pluginsGLPI/genericobject/pull/201/files#diff-c7d2c155f00fc5787c51bca2ac6a2d18R809

**Comment by cedric-anne** [comment]
Hi,

Not sure, but I think that what you tried to do has been handled by #214 and https://github.com/pluginsGLPI/datainjection/pull/122.

Regards

**Comment by cedric-anne** [comment]
@pVesian 

Did you see my last comment ?

Regards

**Comment by cedric-anne** [comment]
Hi,

I close this PR as no answer were given to my latest comments. Feel free to reopen it if you have time to work on it again.

Regards

**Comment by abhishek-rajput-44** [comment]
Hi, I have installed glpi v10.00 on my local machine using XAMPP. Also installed latest plugin generic object management (version 2.12.1) to create new assets object and data / file injection (version 2.11.2) to import data by csv file for created new object. For example i have created new asset object called "Television" and i am using csv file with two columns "Name", "Location" to import data for the same. data is inserted but location field is not reflected in the list view.

Its not working. Can anyone help me to resolve this issue. Where do i have to make changes in file level to work this.

**Pull request closed without merging**
